### ISSUE TITLE
Widgets and Scopes

### ISSUE THREAD

**Issue by chfin** [piever/Widgets.jl#20]
Not sure if this is the right place to ask this.

I'm trying to figure out how scopes and widgets interact. The background is that I would like to create a widget that includes some client side logic, so I need a scope to have the client code react to changes in observables.

However, I'm already stuck at `onimport`. When I just generate a scope, everything works fine:
```julia
function myscope()
    scp = Scope()
    onimport(scp, @js x -> console.log("hi")) # <- this is printed
    scp(dom"div"())
```
But attaching the scope to a widget and displaying the widget doesn't work
```julia
function mywidget()
    scp = Scope()
    onimport(scp, @js x -> console.log("hi")) # <- this won't be printed
    wdg = Widget(scope=scp)
    @layout! wdg dom"div"()
end
```

It seems like the widgets in InteractBase.jl do something similar (e.g. [rangeslider](https://github.com/piever/InteractBase.jl/blob/master/src/slider.jl#L88)), but this combination is not really documented, so I'd appreciate help. I'd also be willing to contribute documentation, once I get this to work.

**Comment by piever** [comment]
There definitely is a bit of a lack of developer docs, as I was a bit unsure whether some things were hacks to get things to work or long term solutions. I'm quite happy with the solutions right now, so I guess it's be good to document them (at Interact.jl, that's the meta repo with all the docs).

In this case what happens is the following. Each widget can (optionally) have an associated scope. For example in your case you could do:
```julia
wdg = Widget(scope = myscope())
```

This can be recoverd with the `scope` accessor function. Say `scope(wdg)` will get you your scope back.

The default layout is to put one component on top of the other (in this case you don't have any components or output) so the default is to put an empty div in the page.

To display the scope in the layout you could do:
```julia
wdg = Widget(scope = myscope())
@layout! wdg scope(_) # _ refers to the widget
```
or in this case the macro doesn't gain you much, so it's also possible to do:

```julia
wdg = Widget(scope = myscope(), layout = scope)
```

A good example or this are the `alert` and `confirmation` widgets (as there you only want to embed the javascript, but no visible html), see for example [here](https://github.com/piever/InteractBase.jl/blob/master/src/output.jl#L54)

**Comment by chfin** [comment]
Thanks a lot, this seems to work indeed. I'll play around with this a bit and share my experience in the Interact repo.
