### ISSUE TITLE
Arrays of numbers shouldn't be rendered as a slider.

### ISSUE THREAD

**Issue by twavv** [piever/Widgets.jl#34]
```julia
@manipulate for i in [1, 2, 3]
    i
end
```
Having a small array means having a slider is clunky and weird. At the very least, **small** arrays (say less than ten minutes?) shouldn't be forced into sliders. Also, when they're not evenly spaced (e.g. `for i in [1, 2, 3, 10]`) the slider isn't the right UI.

Alternatively, we could have tuples work this way.

Tag @kersulis.

**Comment by piever** [comment]
Closing in favor of the tuple solution.
